### ISSUE TITLE
Compilation Error: Type mismatch

### ISSUE THREAD

**Issue by juank88** [vatbub/smartCharger#1]
Hi. Your project got my attention after the battery of my laptop almost blowed up after being 24/7 plugged to the power outlet. Nice work!

However, I am experiencing issues while compiling your code. I get the following error:
 
`ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.7.10:compile (compile) on project smartCharger: Compilation failure                     [ERROR] D:\git projects\smartCharger\src\main\kotlin\Charger.kt:[61,47] Type mismatch: inferred type is TimeUnit but DurationUnit was expected                    `

I have the following environment for the build:  
- Windows 10
- Java SE Development Kit 19.0.1
- apache-maven-3.8.6

The compilation prerequisites section in the Readme is empty, so I don't know if I'm using the correct versions.

I don't know if you are still maintaining this project, but if you decide to give me a hand, it would be great. :)

Thanks in advance and best regards,
JC

**Comment by vatbub** [comment]
Hey, thanks for using my project :) This compiler error is the result of a kotlin upgrade which went under my radar. I fixed it now together with other small things that broke. If you do find more interest in my project, feel free to contribute - especially with the "profiles"-feature, which is still pretty much broken :/ - but don't feel obligated of course ;)
Thanks again and do submit more issues if you are facing any.
Cheers,
Vatbub

**Comment by vatbub** [comment]
Oh and you need to run `git pull origin master` to get the latest changes. Then, run `mvn package` and it should work :)
